removed zero amount fee validation
mojaloop/interop-apis-bc pull request #19
Opened 2024-02-27 10:59 UTC by kyaw-soe-tw

2024-03-05 09:26 UTC, bushjames requested changes
I think the validator itself should use the regular expression from the FSPIOP API specification rather than the current implementation. The current implementation is clearly not in line with the spec. The API specification is clear on permitted values for all API elements.

If the OpenAPI validator is not able to validate all specification rules then this additional validation makes sense, but it MUST be correct to the API specification.

See the spec here for amount validation: https://docs.mojaloop.io/api/fspiop/v1.1/api-definition.html#regular-expression-6

2024-03-05 10:28 UTC, kyaw-soe-tw commented
@bushjames , We still require the validation method for Transfer Amount to disallow a zero-amount value, as the OpenAPI regex validation permits a zero amount in such fields. Therefore, we will retain the validation method for its use.
In this pull request, we are simply removing validation on the fee amount value, as it may be zero according to the corresponding Financial Service Providers (FSPs).

2024-03-06 09:32 UTC, bushjames commented
> @bushjames , We still require the validation method for Transfer Amount to disallow a zero-amount value, as the OpenAPI regex validation permits a zero amount in such fields. Therefore, we will retain the validation method for its use. In this pull request, we are simply removing validation on the fee amount value, as it may be zero according to the corresponding Financial Service Providers (FSPs).

@kyaw-soe-tw understood. many thanks.

2024-03-06 09:34 UTC, bushjames approved these changes

2024-03-06 09:57 UTC, merged